# Generated by Django 3.2.10 on 2021-12-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cf_handle',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
